### ISSUE TITLE
the latest ansible version should not be required to run k8s ansible provision in guest mode

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-entry-k8s#14]
related info from https://github.com/teracyhq-incubator/teracy-dev-entry-k8s/issues/10

**Comment by hieptranquoc** [comment]
related : https://github.com/hashicorp/vagrant/issues/8796

**Comment by hoatle** [comment]
this requires https://github.com/teracyhq-incubator/teracy-dev-k8s/issues/58 so we need to use teracy-dev-k8s v0.4.0

**Comment by hoatle** [comment]
depend #25
